### ISSUE TITLE
No Ip Address or Port are'nt listen

### ISSUE THREAD

**Issue by bosencoding** [madhavajay/selenium-node-phantomjs#1]
Hi,
i have just try this docker but i have problem about port not listen and no ip address of the docker.

Thank You

**Comment by madhavajay** [comment]
Did you set the REMOTEHOST to use the correct hostname?

-e REMOTEHOST=http://mydesktop.local:5555

E.g. mydesktop.local should be the hostname of the MAIN Operating system host e.g. Mac OS or Windows or Linux.

**Comment by bosencoding** [comment]
> `-e REMOTEHOST=http://mydesktop.local:5555`,
> i replace with, 
> `-e REMOTEHOST=http://my-ip_public:5555`
> I have added with --ip=`ip -4 addr show eth0| grep -Po 'inet \K[\d.]+'`, and output message : 
> `docker: Error response from daemon: user specified IP address is supported on user defined networks only.
> `
> This is my full command:
> 
> > docker run -d -e HUB=http://127.0.0.1:4444 -e PORT=5555 -e REMOTEHOST=http://my-ip_public:5555 -p 5555:5555 --ip=\`ip -4 addr show eth0| grep -Po 'inet \K[\d.]+'\` --name=node07  madhavajay/selenium-node-phantomjs
> 
> I run without --ip=`ip -4 addr show eth0| grep -Po 'inet \K[\d.]+'`, no error message, but port 5555 not listening with netstat.
> 
> Any suggestion?

Now it's work, just change address hub with bridge ip

Thank You :)
👍

**Comment by bosencoding** [comment]
<img width="1171" alt="screen shot 2017-08-17 at 9 26 03 am" src="https://user-images.githubusercontent.com/2568845/29393482-2017f844-832e-11e7-8e61-ac58eb8c0b3e.png">
